# Generated by Django 4.2.5 on 2023-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_loan_tran',
            name='balance_loan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
