# Generated by Django 4.2.5 on 2023-11-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_loan_tran_balance_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='billno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
