# Generated by Django 4.2.5 on 2023-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_loan_account_loan_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_transaction',
            name='bank_type',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='from_trans',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='to_trans',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
