# Generated by Django 4.2.5 on 2023-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_loan_transaction_bank_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_transaction',
            name='type',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
