# Generated by Django 4.2.5 on 2023-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_loan_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinvoice',
            name='startdate',
            field=models.DateField(default=''),
        ),
    ]
