# Generated by Django 4.2.5 on 2023-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_recinvoice_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_transaction',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
