# Generated by Django 4.2.5 on 2023-10-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_loan_transaction_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankings_g',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
    ]
