# Generated by Django 4.2.5 on 2023-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_bankings_g_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankings_g',
            name='term',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
