# Generated by Django 4.2.5 on 2023-10-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_bankings_g_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='loan_duration',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
