# Generated by Django 4.2.5 on 2023-10-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_employeeloan_loan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=30)),
                ('term_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee_loan_tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_trans_date', models.DateField()),
                ('particular', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('intrest', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeeloan')),
            ],
        ),
    ]
