# Generated by Django 4.2.5 on 2023-10-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_employeeloan_loan_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeloan',
            name='loan_duration',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='loan_term',
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='loanterm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.loan_duration'),
            preserve_default=False,
        ),
    ]
