# Generated by Django 4.2.5 on 2023-10-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_loan_duration_employee_loan_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_duration',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
            preserve_default=False,
        ),
    ]
