# Generated by Django 4.2.5 on 2023-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_loan_duration_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='balance_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
