# Generated by Django 4.2.5 on 2023-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_employeeloan_loan_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeloan',
            name='loanterm',
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='loan_term',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
