# Generated by Django 4.2.5 on 2023-10-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_employeeloan_balance_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_tran',
            name='employ_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.employeeloan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_loan_tran',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee'),
        ),
    ]
