# Generated by Django 4.2.5 on 2023-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_employeeloan_loanterm_employeeloan_loan_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='loan_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
