# Generated by Django 4.2.5 on 2023-10-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_employee_loan_tran_employ_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_loan_tran',
            old_name='employ_name',
            new_name='emploee_loan',
        ),
    ]
