# Generated by Django 4.2.5 on 2023-10-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_employeeloan_loan_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_loan_tran',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee'),
        ),
    ]
