# Generated by Django 4.2.5 on 2023-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_employee_loan_tran_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_tran',
            name='balance_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
