# Generated by Django 4.2.5 on 2023-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_employee_loan_tran_balance_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_loan_tran',
            name='loan_trans_date',
            field=models.CharField(max_length=100),
        ),
    ]
