# Generated by Django 4.2.5 on 2023-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_employee_loan_tran_loan_trans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankings_g',
            name='bank_status',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
