# Generated by Django 4.2.5 on 2023-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_payrollemployee_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('rec', 'Receipt'), ('roc', 'Record'), ('po', 'Purchase Order'), ('dl', 'Delivery'), ('invoice', 'Invoice')], max_length=10)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
