# Generated by Django 4.2.5 on 2023-11-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_billnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillNumber',
        ),
    ]
