# Generated by Django 4.2.5 on 2023-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_delete_billnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='billno',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
