# Generated by Django 4.2.5 on 2023-11-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_recurring_bill_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bill',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bill',
            name='upi_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
