# Generated by Django 4.2.5 on 2023-11-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_recurring_bill_cheque_no_recurring_bill_upi_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bill',
            name='place_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
