# Generated by Django 4.2.5 on 2023-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_recurring_bill_place_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bill',
            name='vendor_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bill',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Save', 'Save')], default='Draft', max_length=150),
        ),
    ]
