# Generated by Django 4.2.5 on 2023-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_recurring_bill_vendor_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='upi_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
