# Generated by Django 4.2.5 on 2023-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_employeeloan_cheque_no_employeeloan_upi_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='bank_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
