# Generated by Django 4.2.5 on 2023-11-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_employeeloan_bank_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeloan',
            name='bank_id',
        ),
    ]
