# Generated by Django 4.2.5 on 2023-11-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_employeeloan_bank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
