# Generated by Django 4.2.5 on 2023-11-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_employeeloan_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_loan_tran',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_loan_tran',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee_loan_tran',
            name='upi_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
