# Generated by Django 4.2.5 on 2023-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_employee_loan_tran_cheque_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='purchase_order',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
