# Generated by Django 4.2.5 on 2023-11-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_alter_recurring_bill_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='profile_name',
            field=models.IntegerField(default=0),
        ),
    ]
