# Generated by Django 4.2.5 on 2023-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_recurring_bill_refference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bill',
            name='refference',
            field=models.IntegerField(default=1),
        ),
    ]
