# Generated by Django 4.2.5 on 2023-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_remove_invoice_gsttype_customer_placesupply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='prfile',
            field=models.IntegerField(default=0),
        ),
    ]
